### ISSUE TITLE
Breakpoint download

### ISSUE THREAD

**Issue by BaLaLaLs** [aschey/stream-download-rs#134]
Thank you for contributing such an excellent crate. I have a question during my use. If the user encounters network problems while downloading large files, causing the download to be interrupted and unable to continue the previous download, is there any plan to support this feature

**Comment by aschey** [comment]
Are you using the `reqwest` backend? If so, you can enable the `reqwest-middleware` feature and add a retry policy. See [the example here](https://github.com/aschey/stream-download-rs/blob/main/examples/retry_middleware.rs).

**Comment by aschey** [comment]
If you're asking more generically about the ability to restart a download from a specific point, this library isn't really meant for dealing with persistence right now. We could add another file-backed storage method that uses permanent files instead of temporary files, but it's not something I've put much thought into.

**Comment by BaLaLaLs** [comment]
> If you're asking more generically about the ability to restart a download from a specific point, this library isn't really meant for dealing with persistence right now. We could add another file-backed storage method that uses permanent files instead of temporary files, but it's not something I've put much thought into.

Thank you for your answer. I think the feature I really need is to download large files through HTTP range, just like Steam. Users can start or stop at any time, starting from the downloaded location when starting

**Comment by aschey** [comment]
Sounds like saving the download to a non-temporary file combined with a way to persist the download progress somewhere that can be read later is what you need then. Can't promise I'll add something like that anytime soon, but I'd be happy to review a PR if someone wants to work on it.

**Comment by aschey** [comment]
Do you need to be able to stream the file content while it's being downloaded? If not, there's probably a simpler solution that doesn't require using this crate.
