### ISSUE TITLE
Api to recieve status updates from download

### ISSUE THREAD

**Issue by dvdsk** [aschey/stream-download-rs#18]
There is currently no way for a consumer of this lib to know how far nor how fast their download is progressing. 

I plan to implement this in the future.

**Comment by aschey** [comment]
Makes sense, I was thinking about this recently too. How do you feel about a callback-based approach like this?

```rust
let reader = StreamDownload::new_http(...);
reader.on_progress(|progress| do_something_with_progress(progress));
```

That way consumers can handle the event however they choose - log it directly in the callback, send a message to a channel, etc.

**Comment by dvdsk** [comment]
that seem perfect to me! `on_progress` could take something like `FnMut(Progress)`, then `Progress` could be an *Enum* showing the difference between prefetch and play/download.
