### ISSUE TITLE
Support seeking in bounded/adaptive storage

### ISSUE THREAD

**Issue by dvdsk** [aschey/stream-download-rs#27]
```
src/storage/bounded.rs:

//! Because the buffer will never resize, it's important to ensure the buffer is large enough to
//! hold all of the data you will need at once. This needs to account for any seeking that may occur
//! as well as the size of the initial prefetch phase.
```

Suggest seeking further then the bounded storage's capacity is not possible. My use-case is huge podcast episodes which I want to stream without filling up to much disk space or heap memory.

**Comment by aschey** [comment]
I think I answered this here https://github.com/aschey/stream-download-rs/discussions/26. This is likely best handled by a different storage implementation.

**Comment by aschey** [comment]
Closing due to answer above.

**Comment by dvdsk** [comment]
As you indicated you build the bounded/adaptive storage for things like internet radio I have build a (still work in progress) streaming solution specifically for (hours long) podcasts. 

It provides seeking in bounded storage and bandwidth throttling. I would not recommend it for internet radio, stream-download-rs is way better tested and more stable.

If anyone runs into this issue however it might be worth a look: https://github.com/dvdsk/stream-owl

**Comment by aschey** [comment]
Awesome, thanks for the heads up! Is that repo private? Seems to 404 for me.

**Comment by dvdsk** [comment]
> Awesome, thanks for the heads up! Is that repo private? Seems to 404 for me.

good catche! Fixed that :)
