### ISSUE TITLE
Support setting a name for the temporary file for `TempStorageProvider`

### ISSUE THREAD

**Issue by hasezoey** [aschey/stream-download-rs#41]
Please note that i have not run the latest version yet, but i have checked out the documentation and the source code.

It looks like currently the `TempStorageProvider` currently does not provide a way to name the temporary files and if no directory is set will use generic names like `.tmpXXXX`, which will make it somewhat hard to identify what made / uses those files.

**Comment by aschey** [comment]
Hi @hasezoey, you're correct - there currently is no way to customize the underlying temp file beyond setting the directory. I've added a few methods to customize it further [here](#42). Feel free to take a look and let me know if that meets your needs.

**Comment by aschey** [comment]
Released in [v0.5.0](https://crates.io/crates/stream-download/0.5.0), thanks!
