### ISSUE TITLE
Read after download all?

### ISSUE THREAD

**Issue by tramhao** [aschey/stream-download-rs#44]
Hi, firstly thank you so much for this excellent lib. I use it in my repo https://github.com/tramhao/termusic for playing online podcasts and radios.

I have a question though. When I start with version 0.1 of stream download, it works. Recently I update it to version 0.5, and are using adaptiveStorageProvider for podcast, boundedstroageprovider for radio.
Radio works great. Podcast start delay very long time (10-20 seconds). Before in 0.1 it start playing after 1-2 seconds.
Is it because my mistake to use wrong provider? I checked the cache file, it reach almost 100% then start playing.
My code is as below:
```
            let reader = StreamDownload::from_stream(
                stream,
                AdaptiveStorageProvider::new(
                    TempStorageProvider::with_prefix(".termusic-stream-cache-"),
                    // ensure we have enough buffer space to store the prefetch data
                    NonZeroUsize::new(usize::try_from(settings.get_prefetch_bytes() * 2)?).unwrap(),
                ),
                settings,
            )
            .await?;

```

**Comment by aschey** [comment]
The code snippet there seems fine, but what's the reason for using `AdaptiveStorage` here? Do your podcasts sometimes have an unknown length? Is the issue still present when using a different storage provider with podcasts?

**Comment by tramhao** [comment]
You're right. After stop using adaptivestorage and use tempfile storage directly, it works all right. Now podcasts start very fast.

**Comment by aschey** [comment]
Okay, good to hear. If I had to guess, I'd say this `settings.get_prefetch_bytes() * 2` was probably causing the delay. It wouldn't start playback until prefetch was complete.
