### ISSUE TITLE
On xtensa platforms (e.g. ESP32) attempting to read from a stream causes a hard lockup.

### ISSUE THREAD

**Issue by jonahnm** [aschey/stream-download-rs#70]
Here is my test code:
```
let mut settings = Settings::default();
    log::info!("Prefetch buffer size: {}",settings.get_prefetch_bytes());
    let mut reader = tokio::time::timeout(Duration::from_secs(30),StreamDownload::new_http(
        "http://vgmsite.com/soundtracks/legend-of-zelda-the-ocarina-of-time-original-sound-track-1998/xmrmgsutih/35%20Lost%20Woods.flac".parse().unwrap(),
        BoundedStorageProvider::new(
            MemoryStorageProvider,
            NonZeroUsize::new(usize::try_from(settings.get_prefetch_bytes() * 2).expect("Error converting to usize!")).unwrap()
        ),
        settings,
    )).await.expect("Encountered timeout!!!").unwrap();
    log::info!("Reader created!");
    log::info!("Going to attempt to read some bytes!");
    let mut bytes: &mut [u8] = &mut [0;5];
    reader.read_exact(bytes).expect("Failed to read bytes");
    log::info!("Read bytes! {:?}",bytes);
```
And here is the log I get: 
`
I (5114) assistant: Reader created!
I (5114) assistant: Going to attempt to read some bytes!
`
and then nothing happens, implying a hard lockup.

**Comment by jonahnm** [comment]
I will note that this could be an unrelated issue to xtensa, and be an issue with the HTTP stream.

**Comment by aschey** [comment]
I ran that code locally and it worked fine so I suspect it's something to do with the embedded context.  Unfortunately, I don't know much of anything about embedded development and it wasn't something I was thinking about when making this library. I suspect at the very least, there may be some tuning of our dependencies (tokio and reqwest, namely) that may be required.

**Comment by jonahnm** [comment]
Tokio and reqwest work perfectly in my testing.

**Comment by aschey** [comment]
Can you initialize tracing using something like the following:

```rust
 tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::builder()
                .with_default_directive(LevelFilter::TRACE.into())
                .parse("")
                .unwrap(),
        )
        .with_line_number(true)
        .with_file(true)
        .init();
```

and attach the log output?

**Comment by aschey** [comment]
Just thought of something actually. Are you using tokio's single-threaded runtime? If you are and you make a blocking call like `reader.read_exact` or something on the main thread, the stream download task won't be able to progress so that would explain the deadlock.

**Comment by jonahnm** [comment]
> Just thought of something actually. Are you using tokio's single-threaded runtime? If you are and you make a blocking call like `reader.read_exact` or something on the main thread, the stream download task won't be able to progress, resulting in the kind of deadlock you mention.

Ah, I'll try using the multithread runtime.

**Comment by aschey** [comment]
As a side note, it's best to make sure you're not doing any nontrivial blocking IO in an async context anyway. You can use `spawn_blocking` for this (the examples in this repo do the same thing).

```rust
 tokio::task::spawn_blocking(move || {
      let mut bytes: &mut [u8] = &mut [0; 5];
      reader.read_exact(bytes).expect("Failed to read bytes");
      info!("Read bytes! {:?}", bytes);
  })
  .await
```

**Comment by jonahnm** [comment]
Took a while to get multi thread working on xtensa, but now that multithread is working on xtensa, reading bytes works perfectly fine now! Thanks for your help!
