### ISSUE TITLE
Add support for webdav/cloud providers via OpenDAL

### ISSUE THREAD

**Issue by prabirshrestha** [aschey/stream-download-rs#72]
Would be great if [OpenDAL](https://github.com/apache/opendal) support is added. Ton of cloud providers such as S3/Azure Blobs/Webdav/Google Drive/Dropbox support would come for free. 

Here are the list of services supported. https://docs.rs/opendal/latest/opendal/services/index.html

**Comment by aschey** [comment]
That's a neat library! On first glance, it seems this should be doable by implementing the [`SourceStream`](https://docs.rs/stream-download/latest/stream_download/source/trait.SourceStream.html) trait for some type wrapping [`Operator`](https://docs.rs/opendal/latest/opendal/struct.Operator.html).
