### ISSUE TITLE
Fetching error in infinite stream example

### ISSUE THREAD

**Issue by ricott1** [aschey/stream-download-rs#76]
Hello, thanks for the nice work 🙏 

I get the error `Error: Custom { kind: InvalidInput, error: "error fetching https://us2.internet-radio.com/proxy/mattjohnsonradio?mp=/stream: error sending request for url (https://us2.internet-radio.com/proxy/mattjohnsonradio?mp=/stream)" }` when trying to run the example https://github.com/aschey/stream-download-rs/blob/main/examples/infinite_stream.rs .

I also got the same error in one of my applications that is using the repo or if I try different URLs.

I'm running with 
- rodio = "0.19.0"
- stream-download = "0.7.0"
- tokio = { version = "1.39.2", features = ["full"] }

**Comment by aschey** [comment]
Does this URL resolve in your browser? https://us2.internet-radio.com/proxy/mattjohnsonradio?mp=/stream It works fine for me.

**Comment by aschey** [comment]
Make sure you include a TLS provider as well `--features=reqwest-rustls` or `--features=reqwest-native-tls`

**Comment by ricott1** [comment]
The URL resolves fine, the problem was with enabling the extra features, thanks!
