### ISSUE TITLE
StreamDownload::new_http does not work in tokio::spawn()

### ISSUE THREAD

**Issue by csko** [aschey/stream-download-rs#90]
`StreamDownload::new_http` does not work in `tokio::spawn`, however it works with `tokio::spawn_local`, suggesting that it's somehow not handling the `Send` trait properly.

```
use std::io::Read;
use stream_download::storage::temp::TempStorageProvider;
use stream_download::{Settings, StreamDownload};
use tokio::task;

#[tokio::main]
async fn main() {
    // This works:
    // run();

    // This works:
    // let local = task::LocalSet::new();
    // local
    //     .run_until(async move {
    //         task::spawn_local(run()).await.unwrap();
    //     })
    //     .await;

    // This does not work:
    tokio::spawn(run()).await.unwrap();
}

async fn run() {
    println!("starting");
    let mut reader = StreamDownload::new_http(
        "https://filesampleshub.com/download/audio/mp3/sample1.MP3"
            .parse()
            .unwrap(),
        TempStorageProvider::default(),
        Settings::default(),
    )
    .await
    .unwrap();
    let mut buf = Vec::new();
    reader.read_to_end(&mut buf).unwrap();
    println!("len: {}", buf.len());
}
```

This only prints `starting` and hangs.

Used the tokio versions found in Cargo.toml in this repo.

**Comment by aschey** [comment]
`reader.read_to_end(&mut buf)` is a blocking operation which shouldn't be used in an async task. See the examples for how to use `spawn_blocking` to properly use blocking IO.

**Comment by aschey** [comment]
Apologies, I'm assuming you may have copied some code snippets from docs.rs. I had previously tried to fix the examples that used this incorrect pattern here: #83 but I forgot to update the doc tests. This is fixed in the latest release.
